name: Azure_poi_Workflow

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apis/poi/**'
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: Azure CLI Action
          uses: Azure/cli@v1.0.0
          with:
            inlineScript: | 
              echo "Changing directory to ./apis/poi/web..."
              cd "apis/poi/web"
              az acr build --image "devopsoh/api-poi:latest" --registry openhack5qk81i73acr --file Dockerfile .
              az webapp deployment slot swap -g ${{ secrets.RESOURCE_GROUP }} -n openhack5qk81i73poi --slot staging --target-slot production
            
