name: Linux_Container_Workflow_UserProfile

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apis/userprofile/**'
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Docker login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: 'Build and push User Profile image'
          working-directory: apis\userprofile
          run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-userprofile:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-userprofile:latest
        - name: Azure CLI Action
          uses: Azure/cli@v1.0.0
          with:
            inlineScript: | 
              az webapp deployment slot swap -g ${{ secrets.RESOURCE_GROUP }} -n openhack5qk81i73userprofile --slot staging --target-slot production
            
