name: GIPHY generator

on:
  issues:
    types: [open, edited]
  pull_request:
    types: [open, edited]
  issue_comment:
    types: [created, edited]

jobs:
  giphy-generator:
    runs-on: ubuntu-latest
    
    steps:
      - name: GIPHY Generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        with:
          rating: 'g'
          lang: 'en'
