# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apis/userprofile/*'
    
  pull_request:
    branches: 
      - '**'
    paths:
      - 'apis/userprofile/*'

jobs:
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: nmp ci
      working-directory: apis/userprofile/
      run: npm ci
    - name: nmp run
      working-directory: apis/userprofile/
      run: npm run build --if-present
    - name: nmp test
      working-directory: apis/userprofile/
      run: npm test
    - name: Failure
      if: ${{ failure() }}
      run: | 
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
         "title": "BUILD FAILURE for commit: ${{ github.sha }}",
         "body": "This issue was automagically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}"
         }'
