name: userprofile-feature

on:

  pull_request:
    types: [opened, edited]
    branches: 
      - '**'
    paths:
      - 'apis/userprofile/**'
      
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    
    - name: nmp ci
      working-directory: apis/userprofile/
      run: npm ci
      
    - name: nmp run
      working-directory: apis/userprofile/
      run: npm run build --if-present
      
    - name: nmp test
      working-directory: apis/userprofile/
      run: npm test      
